### ISSUE TITLE
对于 SCF CLI，腾讯云函数是计划放弃了？然后主推 serverless framework CLI？

### ISSUE THREAD

**Issue by donhui** [tencentyun/scfcli#15]
目前在函数计算官方文档目录索引找不见 SCF CLI 了。
所以对于 SCF CLI，腾讯云函数是计划放弃了？
然后主推 serverless framework CLI？

**Comment by tinafangkunding** [comment]
您好，目前是计划用 serverless scf component 来替代 scf cli 的，功能是完全覆盖的，您这边使用的时候有问题也欢迎反馈！

https://github.com/serverless-components/tencent-scf

**Comment by donhui** [comment]
了解了，谢谢～
